[package]
name = "pixelrpg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_retrograde = { git = "https://github.com/katharostech/bevy_retrograde", features = ["ldtk"]  }
hex = "0.4.3"